"""add_usage_tracking_tables_and_plan_fields

Revision ID: 7a4ee58279b3
Revises: 2a5ee357c85a
Create Date: 2025-12-04 22:07:14.020620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a4ee58279b3'
down_revision: Union[str, None] = '2a5ee357c85a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.Enum('CHAT', 'RAG', 'AGENT', 'EMBEDDING', 'IMAGE', 'TOOL', name='requesttype'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('tokens_total', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('litellm_call_id', sa.String(length=255), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_conversation_id'), 'usage_records', ['conversation_id'], unique=False)
    op.create_index('ix_usage_records_model', 'usage_records', ['model'], unique=False)
    op.create_index('ix_usage_records_request_type', 'usage_records', ['request_type'], unique=False)
    op.create_index('ix_usage_records_user_created', 'usage_records', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_table('usage_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_credits', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('chat_requests', sa.Integer(), nullable=False),
    sa.Column('rag_requests', sa.Integer(), nullable=False),
    sa.Column('agent_requests', sa.Integer(), nullable=False),
    sa.Column('embedding_requests', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period', name='uq_usage_summary_user_period')
    )
    op.create_index('ix_usage_summaries_period', 'usage_summaries', ['period'], unique=False)
    op.create_index(op.f('ix_usage_summaries_user_id'), 'usage_summaries', ['user_id'], unique=False)
    # Add new columns with server_default for existing rows
    op.add_column('plans', sa.Column('requests_per_month', sa.Integer(), nullable=False, server_default='100'))
    op.add_column('plans', sa.Column('credits_per_month', sa.Integer(), nullable=False, server_default='100'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'credits_per_month')
    op.drop_column('plans', 'requests_per_month')
    op.drop_index(op.f('ix_usage_summaries_user_id'), table_name='usage_summaries')
    op.drop_index('ix_usage_summaries_period', table_name='usage_summaries')
    op.drop_table('usage_summaries')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index('ix_usage_records_user_created', table_name='usage_records')
    op.drop_index('ix_usage_records_request_type', table_name='usage_records')
    op.drop_index('ix_usage_records_model', table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_conversation_id'), table_name='usage_records')
    op.drop_table('usage_records')
    # ### end Alembic commands ###
